### ISSUE TITLE
Need equivilent in PolymerElements v 0.9.x

### ISSUE THREAD

**Issue by mwinters-stuff** [Polymer/core-dropdown-menu#15]
core-dropdown-menu is/was important for creating combo style selections, this needs to have a version in polymer 0.9.x +

**Comment by garrettn** [comment]
:+1: There is no clear replacement for this functionality in Polymer 1.x. Are there any plans to upgrade this component?

**Comment by notwaldorf** [comment]
Yup! There's a PR being worked on, should be ready this week/next week-ish :)

**Comment by garrettn** [comment]
Great news! Thank you.

**Comment by TimvdLippe** [comment]
This was ported to https://github.com/PolymerElements/paper-dropdown-menu/
